### ISSUE TITLE
It doesn't start on Hassio

### ISSUE THREAD

**Issue by giacomocarrozzo** [RobHofmann/HomeAssistant-GreeClimateComponent#133]
**Describe the bug**
It doesn't start on Hassio. 

**Configuration**
```
mqtt:
  broker_url: mqtt://172.0.0.1
  username: mqtt-user
  password: mqtt-user
  retain: ""
devices:
  - hvac_host: 192.168.188.109
    mqtt_topic_prefix: home/greehvac
```

**Platform:**
- Raspberry Pi 3
- Home Assistant 2022.11.4
- Supervisor 2022.11.2
- Operating System 9.3
- Gree HVAC MQTT bridge 1.2.4

**Logs**
s6-overlay-suexec: fatal: can only run as pid 1
