### ISSUE TITLE
AC Sleep setting is not kept when mode/temp is changed

### ISSUE THREAD

**Issue by simonepsp** [RobHofmann/HomeAssistant-GreeClimateComponent#136]
**Describe the bug**
AC Sleep parameter is not kept when mode / temperature is changed. I would like to switch between MODES or TEMPERATURES without having the BEEP sound annoy me (yes I've considered removing the buzzer from the pcb altogether haha. A bit drastic, I know.)

**To Reproduce**
1. Set the AC climate entity to any mode (ie. fan only)
2. Switch its sleep mode input_boolean to true/on
3. Change mode or temperature
4. The sleep mode will be disabled and the AC will sound a noticeable BEEP sound (which I want to suppress, hence the sleep mode)

**Configuration**

* configuration.yaml *
```
# Climate
climate: !include climate.yaml
input_boolean: !include input_boolean.yaml

```

*  climate.yaml *

```
# Downstairs
- platform: climate_group
  name: 'Downstairs ACs'
  temperature_unit: C
  entities:
  - climate.kitchen_ac
  - climate.living_room_ac

- platform: gree
  name: Living Room AC
  host: [REDACTED]
  port: 7000
  mac: '[redacted]'
  target_temp_step: 1
  temp_sensor: sensor.gree_living_room_ac_temperature
  lights: input_boolean.gree_living_room_ac_light
  xfan: input_boolean.gree_living_room_ac_xfan
  health: input_boolean.gree_living_room_ac_health
  sleep: input_boolean.gree_living_room_ac_sleep
  powersave: input_boolean.gree_living_room_ac_powersave
  
- platform: gree
  name: Kitchen AC
  host: [REDACTED]
  port: 7000
  mac: [REDACTED]
  target_temp_step: 1
  temp_sensor: sensor.gree_kitchen_ac_temperature
  lights: input_boolean.gree_kitchen_ac_light
  xfan: input_boolean.gree_kitchen_ac_xfan
  health: input_boolean.gree_kitchen_ac_health
  sleep: input_boolean.gree_kitchen_ac_sleep
  powersave: input_boolean.gree_kitchen_ac_powersave
 
# Upstairs
- platform: climate_group
  name: 'Upstairs ACs'
  temperature_unit: C
  entities:
  - climate.yulia_ac
  - climate.simon_office_ac
  - climate.bedroom_ac
  
- platform: gree
  name: Yulia AC
  host: [REDACTED]
  port: 7000
  mac: [REDACTED]
  target_temp_step: 1
  temp_sensor: sensor.gree_yulia_temperature
  lights: input_boolean.gree_yulia_ac_light
  xfan: input_boolean.gree_yulia_ac_xfan
  health: input_boolean.gree_yulia_ac_health
  sleep: input_boolean.gree_yulia_ac_sleep
  powersave: input_boolean.gree_yulia_ac_powersave
  
- platform: gree
  name: Simon Office AC
  host: [REDACTED]
  port: 7000
  mac: [REDACTED]
  target_temp_step: 1
  temp_sensor: sensor.gree_simon_office_ac_temperature
  lights: input_boolean.gree_simon_office_ac_light
  xfan: input_boolean.gree_simon_office_ac_xfan
  health: input_boolean.gree_simon_office_ac_health
  sleep: input_boolean.gree_simon_office_ac_sleep
  powersave: input_boolean.gree_simon_office_ac_powersave

- platform: gree
  name: Bedroom AC
  host: [REDACTED]
  port: 7000
  mac: [REDACTED]
  target_temp_step: 1
  temp_sensor: sensor.gree_bedroom_ac_temperature
  lights: input_boolean.gree_bedroom_ac_light
  xfan: input_boolean.gree_bedroom_ac_xfan
  health: input_boolean.gree_bedroom_ac_health
  sleep: input_boolean.gree_bedroom_ac_sleep
  powersave: input_boolean.gree_bedroom_ac_powersave
```

* input_boolean.yaml *

```
# CLIMATE BOOLEANS
# - Living Room
gree_living_room_ac_light:
  name: "Living Room AC Lights"
gree_living_room_ac_xfan:
  name: "Living Room AC X-Fan"
gree_living_room_ac_health:
  name: "Living Room AC Health mode"
gree_living_room_ac_sleep:
  name: "Living Room AC Sleep"
gree_living_room_ac_powersave:
  name: "Living Room AC Power Save"

# - Kitchen
gree_kitchen_ac_light:
  name: "Kitchen AC Lights"
gree_kitchen_ac_xfan:
  name: "Kitchen AC X-Fan"
gree_kitchen_ac_health:
  name: "Kitchen AC Health mode"
gree_kitchen_ac_sleep:
  name: "Kitchen AC Sleep"
gree_kitchen_ac_powersave:
  name: "Kitchen AC Power Save"
  
# - Bedroom
gree_bedroom_ac_light:
  name: "Bedroom AC Lights"
gree_bedroom_ac_xfan:
  name: "Bedroom AC X-Fan"
gree_bedroom_ac_health:
  name: "Bedroom AC Health mode"
gree_bedroom_ac_sleep:
  name: "Bedroom AC Sleep"
gree_bedroom_ac_powersave:
  name: "Bedroom AC Power Save"
  
# - Simon Office
gree_simon_office_ac_light:
  name: "Simon Office AC Lights"
gree_simon_office_ac_xfan:
  name: "Simon Office AC X-Fan"
gree_simon_office_ac_health:
  name: "Simon Office AC Health mode"
gree_simon_office_ac_sleep:
  name: "Simon Office AC Sleep"
gree_simon_office_ac_powersave:
  name: "Simon Office AC Power Save"
  
# - Yulia Office
gree_yulia_ac_light:
  name: "Yulia Office AC Lights"
gree_yulia_ac_xfan:
  name: "Yulia Office AC X-Fan"
gree_yulia_ac_health:
  name: "Yulia Office AC Health mode"
gree_yulia_ac_sleep:
  name: "Yulia Office AC Sleep"
gree_yulia_ac_powersave:
  name: "Yulia Office AC Power Save"
```

**Expected behavior**
I'd expect "sleep" to stay on/true even if I change the climate entity's temperature or mode.

**Platform:**
 - OS: HASSIO
 - Custom component installed from HACS

Everything else works great! Thank you :)
