### ISSUE TITLE
How to access/expose separate Entities ?

### ISSUE THREAD

**Issue by luckylinux** [RobHofmann/HomeAssistant-GreeClimateComponent#158]
**Is your feature request related to a problem? Please describe.**
This is a very nice Integration !

I managed, after lots of frustration with my Rock 5B SBC and Hostapd (had to change WiFi Adapter since the other one was causing lots of Instability), to get the Integration up and Running.

I gave it a little test by "Cool" to "25°C" and the Light Indicators on the Unit matched the Settings (and it started cooling down the Room).

Therefore I believe you can add my unit to the Compatible List (Denmark): **Copmax Air-Air Heatpump GWH12QC-K6DNA5F 3.5kW**.

HOWEVER: **the Password for the Wifi Network must either be <= 32 Characters and/or NOT contain any special Symbol**. With the Password I used for all my other ESP32 Devices, the Air Conditioner would keep on Connecting-Disconnecting-Connecting-Disconnecting-... all the time without even getting an IP Address.

I'd like however to know how to "access" / "expose" the separate entities individually, as I never had a single Entity to be managed (only started playing with Home Assistant in the last 9 months or so).

![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/7126291/824d4aad-72ac-45b1-99bb-79493dbea206)

**Describe the solution you'd like**
Some further explanation in the README would be highly appreciated, on how to "access" / "expose" / "separate" the sub-entities of this Device.

Maybe the "Issue" (or Feature) is that this Integration treats the whole Air Conditioning Unit as an "Entity" and NOT a Device WITH Entities.

Please correct me if I'm wrong.

I see some things might be done in Developer Tools -> States and Developer Tools -> Services, but it feels a bit different than usual.

**Describe alternatives you've considered**

**Additional context**

**Comment by RobHofmann** [comment]
This integration simply follows the home assistant guidelines for a "climate" device. It is not something we can deliberately choose. Fortunately this is the case, or all the different implementations would make configuring climate entities a jungle :).

But lets try to solve your questions:
What subentities are you looking for exactly or what are you trying to achieve. Maybe I can help you with achieving those goals.

**Comment by luckylinux** [comment]
Thank you for your quick Answer.

Essentially I'd like to have a "Single-Item" interface, which I might directly access from Nodered (if I can get it up and running) or from a Python Program using MQTT.

So a Single "Switch" for ON/OFF, a Input Box / Slider for "Temperature", a Select Box for "Mode" (Cool, Heat, Fan, etc). Similarly to how many ESPHome Devices work basically.

This is for instance what my Batter-Inverter ESP32 looks like (part of it at least):
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/7126291/f725d017-4590-4e90-94cb-94123f6cc9a5)

**Comment by RobHofmann** [comment]
Ah right, there is some features like template controls.

For example a template switch. Documentation can be found here:
https://www.home-assistant.io/integrations/switch.template/

With this template switch you could do something like (untested :)):
```yaml
switch:
  - platform: template
    switches:
      auto_cool:
        value_template: "{{ is_state('switch.source', 'on') }}"
        turn_on:
          - service: climate.set_temperature
            data:
              temperature: 21
              hvac_mode: cool
            target:
              entity_id: climate.my_ac
        turn_off:
          - service: climate.turn_off
            target:
              entity_id: climate.my_ac

```

After adding the above you will have an entity called switch.auto_cool.

Hope this helps :).
