### ISSUE TITLE
Unable to connect to ac

### ISSUE THREAD

**Issue by ShiinaKin** [RobHofmann/HomeAssistant-GreeClimateComponent#174]
**Describe the bug**

Setup of platform gree is taking longer than 60 seconds. Startup will proceed without waiting any longer.
I have tried to reset the WiFi of A/C and other methods in the issues.

**Configuration**

```yaml
- platform: gree
  name: Badroom-AC
  host: 192.168.1.163
  port: 7000
  mac: 'e8:16:56:4f:fa:f0'
  target_temp_step: 1
  encryption_version: 2
  temp_sensor: sensor.ble_temperature_3
  lights: input_boolean.bedroom_ac_lights
  health: input_boolean.bedroom_ac_health
  sleep: input_boolean.bedroom_ac_sleep
  powersave: input_boolean.bedroom_ac_powersave
```

**Platform:**

 - OS: Ubuntu Docker HA 2024.6.2
 - Browser chrome126
 - Version 2.11.0

**Additional context**
It should be noted that, my firmware of A/C is v1.25, maybe they made some changes to the protocol.

**Logs**

```text
2024-06-16 09:03:37.554 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2024-06-16 09:03:37.554 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2024-06-16 09:03:37.554 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2024-06-16 09:03:37.555 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2024-06-16 09:03:37.578 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.1.163, 7000, 10, {"cid": "app","i": 1,"pack": "Jtod3XIt89K2vs2Bb39BUckg7tMAzgfkbQU3H+DJw/DAIDhZ2Qc4K46l9aCGHseEwf35XMKtIPQDq97Iev6J","t":"pack","tcid":"e816564ffaf0","uid": 0, "tag" : "bVOOJvDa6Gh7tX1aARVZAA=="})
2024-06-16 09:03:47.582 ERROR (MainThread) [homeassistant.components.climate] Setup of platform gree is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

**Comment by RobHofmann** [comment]
Did you also try the v1 encryption?

**Comment by ShiinaKin** [comment]
> Did you also try the v1 encryption?

This is indeed something I did not try, as the README say that v1.21 should use encryption version 2, and now it works fine, thanks for the reply.

Also hope to specify this in the README, that may help somebody like me.

A/C model is KFG-35GW(35549)FNhAc-B1(WIFI)

**Comment by Tempmail1234-pass** [comment]
@ShiinaKin It worked for you using the v1 encryption? can you send me the full climate.yaml and configuration.yaml files please?

**Comment by ShiinaKin** [comment]
> @ShiinaKin It worked for you using the v1 encryption? can you send me the full climate.yaml and configuration.yaml files please?

```yaml
- platform: gree
  name: Badroom-AC
  host: 192.168.1.201
  port: 7000
  mac: 'e816564ffaf0'
  target_temp_step: 1
  encryption_version: 1
  uid: 0
  temp_sensor: sensor.ble_temperature_3
  xfan: input_boolean.bedroom_ac_xfan
  lights: input_boolean.bedroom_ac_lights
  health: input_boolean.bedroom_ac_health
  sleep: input_boolean.bedroom_ac_sleep
  powersave: input_boolean.bedroom_ac_powersave
  auto_xfan: true
  auto_light: false
  horizontal_swing: true
  ```

**Comment by ShiinaKin** [comment]
> @ShiinaKin It worked for you using the v1 encryption? can you send me the full climate.yaml and configuration.yaml files please? Also do I need to first connect my A/C to gree+ app first and then run download the integration or do I need to reset my A/C wifi by powering off and pressing wifi and mode first?

My steps:

1. use gree+ and add a/c as my device, it will also let the a/c connect to your own wifi
2. find the mac in the device info footer, and find it's ip by router management
3. option: fixed the ip with mac by router management
4. try to ping the ip of a/c, it will get resp if everything is ok
5. edit climate.yaml & restart HA
6. done

may helpful for u

**Comment by Tempmail1234-pass** [comment]
@ShiinaKin The A/C name in Gree+ app must be the same for the climate.yaml file?
Also the Mac adress should be separeted by '-' or ':', am I wrong?

**Comment by ShiinaKin** [comment]
> @ShiinaKin The A/C name in Gree+ app must be the same for the climate.yaml file? Also the Mac adress should be separeted by '-' or ':', am I wrong?

don't need to be same, and as you see `"tcid":"e816564ffaf0"`, the mac finally will be processing like this partten, but you also could try it, i can use it with out split.

**Comment by Tempmail1234-pass** [comment]
@ShiinaKin Thanks.
I don't see any logs, is my configuration.yaml fine?
```
# Loads default set of integrations. Do not remove.
default_config:
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    custom_components.gree: debug
    custom_components.gree.climate: debug
    

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml
```

Do I only have to click?

> Restart Home Assistant? This will interrupt all running automations and scripts.
