### ISSUE TITLE
[not a bug] v2.13 works on firmware v1.21

### ISSUE THREAD

**Issue by NikolaSivkov** [RobHofmann/HomeAssistant-GreeClimateComponent#181]
Hello there, 
After some trial and error, i got the v2.13 to work with my gree AC, that are on firmware v1.21!
Thank you for your efforts and to the contributor of the PR for v2.13

Here's my config

```yaml
- platform: gree
  name: Bedroom AC
  host: 192.168.1.x
  port: 7000
  mac: '94:24:b8:xx:xx:xx'
  #encryption_key: 'a3K8Bx%2r8Y7GREE' < not needed
  encryption_version: 2 # < MUST BE V2
  target_temp_step: 1
  temp_sensor: sensor.bedroom_ac_temp
  lights: input_boolean.bedroom_ac_lights
  xfan: input_boolean.bedroom_ac_xfan
  health: input_boolean.bedroom_ac_health
  sleep: input_boolean.bedroom_ac_sleep
  powersave: input_boolean.bedroom_ac_powersave
  eightdegheat: input_boolean.bedroom_ac_eightdegheat
  air: input_boolean.bedroom_ac_air
  target_temp: input_number.bedroom_ac_target_temp
```
