### ISSUE TITLE
"Anti Direct Blow" didn't work after v2.13.0

### ISSUE THREAD

**Issue by macming** [RobHofmann/HomeAssistant-GreeClimateComponent#182]
I've got same model of AC like OP's in #162, "Anti Direct Blow" function works properly by using the file from this reply > @red3 can U try attached file, if this is working or throw any errors? [climate.txt](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/15456006/climate.txt).

After I updated to v2.13.0, the switch keeps switching back after clicked and  "Anti Direct Blow" is not working anymore.

Hope you can fix the problem, thanks.

Here's my "climate.yaml" and "input_boolean.yaml"
```
  - platform: gree
  name: Gree AC
  host: 192.168.50.50
  port: 7000
  mac: 'xx:xx:xx:xx:xx:xx'
  target_temp_step: 1
  temp_sensor: sensor.a4c13896cef4_temperature
  health: input_boolean.gree_ac_health
  sleep: input_boolean.gree_ac_sleep
  anti_direct_blow: input_boolean.gree_ac_anti_direct_blow
```

```
# CLIMATE BOOLEANS
gree_ac_health:
  name: "Health"
gree_ac_sleep:
  name: "Sleep"
gree_ac_anti_direct_blow:
  name: "Anti Direct Blow"
```
