### ISSUE TITLE
Support for Toggling the AC panel light

### ISSUE THREAD

**Issue by Suleiman700** [RobHofmann/HomeAssistant-GreeClimateComponent#204]
This integration works very well, Good job!

But I have a question
In the main Gree integration there was an option to toggle the AC panel lights, Is this possible to integrate?

**Comment by krismarc** [comment]
I am able to control it using this integration, including all other features.

if you set eg. `lights: input_boolean.salon_ac_lights` in your configuration yaml, then you are able to change if the panel lights or not.

**Comment by Suleiman700** [comment]
@krismarc 
Can you give me an example?
It is not working for me.

I have already setup the climate.yaml that contains the AC details like ip, mac ...etc
just missing the config line that should put inside the configuration.yaml

**Comment by RobHofmann** [comment]
configuration.yaml
```yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
```

climate.yaml
```yaml
- platform: gree
  name: Zolderkamer AC
  host: 192.168.10.2
  port: 7000
  mac: 'ab:ab:ab:ab:ab:ab'
  timeout: 10
  target_temp_step: 1
  lights: input_boolean.zolderkamer_ac_lights
  xfan: input_boolean.zolderkamer_ac_xfan
  health: input_boolean.zolderkamer_ac_health
  sleep: input_boolean.zolderkamer_ac_sleep
  powersave: input_boolean.zolderkamer_ac_powersave
  auto_xfan: input_boolean.zolderkamer_ac_auto_xfan
  auto_light: input_boolean.zolderkamer_ac_auto_lights
  max_online_attempts: 15
  disable_available_check: true
```

input_boolean.yaml
```yaml
zolderkamer_ac_lights:
  name: Lights

zolderkamer_ac_xfan:
  name: XFan

zolderkamer_ac_auto_lights:
  name: Auto Lights

zolderkamer_ac_auto_xfan:
  name: Auto XFan

zolderkamer_ac_health:
  name: Health

zolderkamer_ac_sleep:
  name: Sleep

zolderkamer_ac_powersave:
  name: Powersave
```
