### ISSUE TITLE
MODE not visible

### ISSUE THREAD

**Issue by TopoAS** [RobHofmann/HomeAssistant-GreeClimateComponent#244]
**Describe the bug**
I added the devices on my homeassistant
i can see them as climate.ac_living_2 and climate.ac_living_3
i can controll them from climate cards 
so everything work fine
but i need to use an automation to turn on ar of the devices or to chenge the mode (from heat to cool etc)
so:

in automations the ac's are not identified as devices but i can find them as entitys
but when i chose the entity ac_living_3 or ac_living_2 using state i can only see the folowing attributes

min target temperature
max target temperature
target temperature step
curent temperature
target temperature
fan mode
swingmode
supported features

so no atribute to give info abouthe the mode or the status of the AC 
Heat, Cool, on, OFF

what i am missing? 

**To Reproduce**
CREATE AUTOMATIONS

**Configuration**
climate.yaml
- platform: gree
  name: AC_Living
  host: 192.168.50.230
  port: 7000
  mac: '94:24:B8:4E:1C:CA'
  encryption_version: 2
  target_temp_step: 1
  
- platform: gree
  name: AC_Birou
  host: 192.168.50.9
  port: 7000
  mac: 'F4:91:1E:D2:34:93'
  target_temp_step: 1

**Platform:**
 - OS: HASSIO
 - Browser chrome
 - Version 2.15.2

**Comment by RobHofmann** [comment]
I'm not entirely sure what you mean, but heres an automation from my side:

```yaml
- alias: Master Bedroom - Cool in the evening with hot weather when we are home
  id: mb_cool_with_hot_weather
  trigger:
    - platform: time
      at: '20:00:01'
    - entity_id: sensor.presence
      platform: state
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.mean_outside_temperature_1d
            above: 23
      - condition: state
        entity_id: sensor.presence
        state: home
  action:
    - service: script.turn_on
      target:
        entity_id: script.ac_slaapkamer_cool
```

My script for activating cool mode:
```yaml
ac_slaapkamer_cool:
  alias: Koelen
  sequence:
  - service: switch.turn_off
    data:
      entity_id: switch.slaapkamer_ac_turn_on_timer_switch
  - delay:
      milliseconds: 500
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.slaapkamer_ac
      hvac_mode: cool
  - delay:
      milliseconds: 500
  - service: climate.set_temperature
    data:
      entity_id: climate.slaapkamer_ac
      temperature: 21
  - delay:
      milliseconds: 500
  - service: climate.set_fan_mode
    data:
      entity_id: climate.slaapkamer_ac
      fan_mode: Quiet
  - delay:
      milliseconds: 500
  - service: climate.set_swing_mode
    data:
      entity_id: climate.slaapkamer_ac
      swing_mode: Fixed in the upmost position
```

You should be able to read the state of the climate.<nameofyourclimatedevice> for the actual mode it is on.

Hope this helps.

**Comment by HK-Liu** [comment]
I have a similar problem:
`alias: open
description: ""
triggers:
  - trigger: state
    entity_id:
      - event.xiaomi_cn_772583221_rd08_virtual_event_e_7_1
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: climate.wo_shi_kong_diao_2
        attribute: hvac_modes
        state: "off"
actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: cool
    target:
      entity_id: climate.wo_shi_kong_diao_2
mode: single
`
this didnt work, cause there was no condition state attribute called "hvac_modes", but in my situation, really need to konw the current hvac_modes before change it.

**Comment by RobHofmann** [comment]
![Image](https://github.com/user-attachments/assets/f4f5c0bb-db55-4301-b41c-ea18366d97fd)

The hvac mode is just the state of the entity itself (see screenshot).

So the condition would be something like this:
```yaml
condition: state
entity_id: climate.wo_shi_kong_diao_2
state: "off"
```
