### ISSUE TITLE
Current temperature is incorrect due to TEMP_OFFSET

### ISSUE THREAD

**Issue by yinseny** [RobHofmann/HomeAssistant-GreeClimateComponent#246]
**Describe the bug**
Current temperature is incorrect.

**To Reproduce**
1. Go to 'Settings' -> 'Entities'
2. Click on any Gree Climate component to open detail dialog
4. Current temperature is shown incorrectly

**Configuration**
```yaml
- platform: gree
  name: ...
  host: ...
  port: 7000
  mac: ...
  target_temp_step: 1
  lights: input_boolean.living_room_ac_lights
  xfan: input_boolean.living_room_ac_xfan
  health: input_boolean.living_room_ac_health
  sleep: input_boolean.living_room_ac_sleep
  powersave: input_boolean.living_room_ac_powersave
  air: input_boolean.living_room_ac_air
  horizontal_swing: true
  anti_direct_blow: input_boolean.living_room_ac_anti_direct_blow

```

**Expected behavior**
Current temperature shown correctly

**Screenshots**
![Image](https://github.com/user-attachments/assets/8e762ba5-0f48-43a9-8c36-49b7dfcfec58)

**Platform:**
 - OS: HomeAssistant docker container
 - Browser: chrome
 - Version: 2.15.3

**Additional context**
I'm using Celsius, and noticed in the debug log that `TemSen` is actually correct. However, it was later added with an offset of `-40` (`TEMP_OFFSET`) which causing the issue.

![Image](https://github.com/user-attachments/assets/e14fda82-d1ab-4076-afa5-84338b9ee387)

**Logs**

[home-assistant_gree_2025-05-19T13-55-51.689Z.log](https://github.com/user-attachments/files/20298304/home-assistant_gree_2025-05-19T13-55-51.689Z.log)
