### ISSUE TITLE
Help for call service in raw config ui trought cards

### ISSUE THREAD

**Issue by mascimax** [RobHofmann/HomeAssistant-GreeClimateComponent#36]
Hi pls help,
i need to call service swing,mode,fan etc trought button, i make this cards but not work:

CARD 1
type: 'custom:button-card'
icon: 'mdi:air-conditioner'
color: 'rgb(28, 128, 199)'
tap_action:
  action: call-service
  service: climate.set_swing_mode
  entity_id: climate.condizionatore
  data: 1
  swing_mode: 1
  name: Swing
show_icon: true
show_name: true

Give me this error:
Fallita chiamata a servizio climate/set_swing_mode . required key not provided @ data['swing_mode']

CARD2 NO WORK
type: 'custom:button-card'
icon: 'mdi:air-conditioner'
color: 'rgb(28, 128, 199)'
tap_action:
  action: null
  service: climate.set_temperature
  data: null
  entity_id: hvac_mode
  temperature: 20
  operation_mode: cool

TKs

**Comment by RobHofmann** [comment]
I think you are missing some information. I guess it should be something like this (not tested):

```
      tap_action:
        action: call-service
        service: climate.set_swing_mode
        service_data:
          entity_id: climate.condizionatore
          swing_mode: 'Fixed in the upmost position'
```

If you want to know how to set the button up, please refer to the official Home Assistant forums.
