### ISSUE TITLE
No possible disable sleep

### ISSUE THREAD

**Issue by claudiosala80** [RobHofmann/HomeAssistant-GreeClimateComponent#44]
**Describe the bug**
I added the option for sleep, with an input Boolean
When I set the button to true, the sleep is enabled on the final device.
If I make the button change status, the sleep is not disabled on the device

my yaml
- platform: gree
  name: Condizionatore camera
  host: 192.168.x.x
  port: 7000
  mac: '123456789'
  target_temp_step: 1
  sleep: input_boolean.bedroom_ac_sleep

**Platform:**
 - OS: Hassbian
 - Browser: Chrome
 - Version: 0.10x

**Comment by RobHofmann** [comment]
How do you implement this boolean? Can you share the input_boolean.bedroom_ac_sleep entity?

**Comment by claudiosala80** [comment]
input_boolean:
  bedroom_ac_sleep:
    name: Condizionatore camera sleep
    initial: off

**Comment by RobHofmann** [comment]
Can you turn on debugging for this component and paste the debug log? The boolean seems fine.

**Comment by claudiosala80** [comment]
Here!
When I turn on the device, it was with sleep on and the boolean on lovelace was correct.
I set it to off, the device did sound, but sleep still on and after a sync also on lovelace was still on

I did operation around 16:22

[[custom_components.gree.climate].log](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/3892567/custom_components.gree.climate.log)

**Comment by RobHofmann** [comment]
Hmm. I dont use/have this feature, so its hard for me to debug.

@wjketting implemented this feature. maybe he can aid us with this issue.

**Comment by claudiosala80** [comment]
I don't know python and so I don't how debug

**Comment by wacher74** [comment]
I experienced similar strange thing about sleep mode, finally I gave it up and I implemented this feature via automation (temp decreasing/increasing + quiet mode at specified time).
I'm not use input_boolean for controling at all, because its icon don't change color (Home Assistant it is very messy in this term). I made template switches for control AC.
(Power on/off, Quiet mode and panel lights, Cold plasma/health)

**Comment by claudiosala80** [comment]
> I experienced similar strange thing about sleep mode, finally I gave it up and I implemented this feature via automation (temp decreasing/increasing + quiet mode at specified time).
> I'm not use input_boolean for controling at all, because its icon don't change color (Home Assistant it is very messy in this term). I made template switches for control AC.
> (Power on/off, Quiet mode and panel lights, Cold plasma/health)

It is something you like to share with me?
I want "get inspiration" from what you did!

**Comment by wacher74** [comment]
Here are some code snipet.
I have Gree Amber (climate.gree_ac_1).

```
## Switches for control
switch:
- platform: template
  switches:
    ac1_onoff:
        friendly_name: 'AC1 power'
        value_template: >-
          {% if states('climate.gree_ac_1') != 'off' %}
            on
          {% else %}
            off
          {% endif %}

        turn_on:
        - entity_id: climate.gree_ac_1
          service: climate.turn_on

        turn_off:
        - entity_id: climate.gree_ac_1
          service: climate.turn_off

    ac1_quiet:
        friendly_name: 'AC1 quiet mode'
        icon_template: 'mdi:headphones'
        value_template: >-
          {% if state_attr('climate.gree_ac_1', 'fan_mode') == 'Quiet' %}
            on
          {% else %}
            off
          {% endif %}

        turn_on:
        - entity_id: climate.gree_ac_1
          service: climate.set_fan_mode
          data:
            fan_mode: 'Quiet'

        turn_off:
        - entity_id: climate.gree_ac_1
          service: climate.set_fan_mode
          data:
            fan_mode: 'Auto'

    ac1_panel_light:
        friendly_name: 'AC1 panel light'
        icon_template: 'mdi:lightbulb-on'
        value_template: "{{ states('input_boolean.ac1_panel_light') }}"

        turn_on:
        - entity_id: input_boolean.ac1_panel_light
          service: input_boolean.turn_on

        turn_off:
        - entity_id: input_boolean.ac1_panel_light
          service: input_boolean.turn_off

    ac1_cold_plasma:
        friendly_name: 'AC1 Health (cold plasma)'
        icon_template: 'mdi:pine-tree'
        value_template: "{{ states('input_boolean.ac1_health') }}"

        turn_on:
        - entity_id: input_boolean.ac1_health
          service: input_boolean.turn_on

        turn_off:
        - entity_id: input_boolean.ac1_health
          service: input_boolean.turn_off





## temperature controlling at specified time, I use AC for heating now.
## 22:00 22C, quiet on
## 07:00 23C
## 08:00 24C, quiet off


automation:
- alias: 'Klíma fűtés, 22:00, 22 fok, quiet mode on'
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: switch.turn_on
      entity_id: switch.ac1_quiet # fan mode quiet
    - delay:
        seconds: 5
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 22


- alias: 'Klíma fűtés, 07:00, 23 fok'
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 23

- alias: 'Klíma fűtés, 08:00, 24 fok, quiet mode off'
  trigger:
  - platform: time
    at: '08:00:00'
  condition:
    condition: state
    entity_id: climate.gree_ac_1
    state: 'heat'
  action:
    - service: switch.turn_off
      entity_id: switch.ac1_quiet # fan mode: Auto lesz
    - delay:
        seconds: 5
    - service: climate.set_temperature
      entity_id: climate.gree_ac_1
      data_template:
        temperature: 24

```
